package com.example.demo;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
@CrossOrigin
public class AppartmentController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private AppartmentRepository appartmentRepository;
    @Autowired
    private BookingRepository bookingRepository;
    @PutMapping("user/updateApp")
    public @ResponseBody
    String changeApp(@RequestBody String jsonStr) throws JSONException {
        JSONObject obj=new JSONObject(jsonStr);
        Integer id=obj.getInt("id");
        appartment n=this.appartmentRepository.findById(id).get();
        n.setAddress(obj.getString("address"));
        n.setAllowPets(obj.getBoolean("pets"));
        n.setAllowPets(obj.getBoolean("smoke"));
        n.setCapacity(obj.getInt("capacity"));
        n.setFloor(obj.getInt("floor"));
        n.setHasheat(obj.getBoolean("ac"));
        n.setHasParking(obj.getBoolean("parking"));
        n.setHasWifi(obj.getBoolean("wifi"));
        n.setIdAvailable(true);
        n.setPrice(obj.getInt("price"));
        n.setCapacity(obj.getInt("capacity"));
        n.setLocation(obj.getString("location"));
        n.setHasElevator(obj.getBoolean("lift"));
        n.setDescription(obj.getString("description"));
        n.setLongitude(obj.getDouble("longitude"));
        n.setLatitude(obj.getDouble("latitude"));
        n.setType(obj.getString("type"));
        n.setAccessInfo(obj.getString("accessInfo"));
        n.setNumberOfBeds(obj.getInt("numberOfBeds"));
        JSONArray jArray=obj.getJSONArray("Dates");
        ArrayList<String> listdata = new ArrayList<String>();
        if (jArray != null) {
            for (int i=0;i<jArray.length();i++){
                listdata.add(jArray.getString(i));
            }
        }
        n.setDates(listdata);
        //n.setDates((ArrayList<String>)obj.getJSONArray("Dates"));
        appartmentRepository.save(n);
        return "OK";
    }
    @PostMapping(path="/newApartment")
    public @ResponseBody Integer addNewAppartment(@RequestBody String jsonStr/*,@RequestParam("img")MultipartFile file*/) throws JSONException, IOException {

        JSONObject jObject = new JSONObject(jsonStr);
        String tempName=jObject.getString("Ownername");
        Optional<User> result=userRepository.findById(tempName);

        //if(!result.get().getOwner())
        //  return "USER DOEN'T HAVE APPARTMENT OWNER PRIVILEGES";
        appartment n=new appartment();

        n.setSize((float) jObject.getDouble("size"));
        n.setOwnername(jObject.getString("Ownername"));
        n.setHasheat(jObject.getBoolean("hasHeat"));
        n.setFloor(jObject.getInt("floor"));
        n.setPrice(jObject.getInt("Price"));
        n.setIdAvailable(true);
        n.setAllowPets(jObject.getBoolean("AllowPets"));
        n.setAllowSmoking(jObject.getBoolean("AllowSmoking"));
        n.setAddress(jObject.getString("Address"));
        n.setHasParking(jObject.getBoolean("HasParking"));
        n.setHasWifi(jObject.getBoolean("HasWifi"));
        n.setCapacity(jObject.getInt("capacity"));
        JSONArray jArray=jObject.getJSONArray("Dates");
        ArrayList<String> listdata = new ArrayList<String>();
        if (jArray != null) {
            for (int i=0;i<jArray.length();i++){
                listdata.add(jArray.getString(i));
            }
        }
        n.setDates(listdata);
        ///now it is time to set location
        n.setLocation(jObject.getString("country")+"+"+jObject.getString("town")+"+"+jObject.getString("neighborhood"));
        //n.setMain_pic((byte[]) jObject.get("pic"));
        appartmentRepository.save(n);
        return n.getId();
    }
    @GetMapping("/allApartments")
    public @ResponseBody Iterable<appartment> getAllAppartments(/*@RequestBody String jsonStr*/)throws JSONException
    {
        return appartmentRepository.findAll();
    }
    @GetMapping("user/AppByUsr")
    public @ResponseBody Iterable<appartment> getApartmentsByUsrID(@RequestParam("username") String usn) throws JSONException
    {

        Optional<User> test =userRepository.findById(usn);
        if(!test.isPresent())
            return null;
        List<appartment> result=appartmentRepository.findByownernameAllIgnoringCase(usn);
        return  result;
    }
    @GetMapping("Appartments/ById")
    public @ResponseBody Optional<appartment> findAppById(@RequestParam("id")Integer id){
        return this.appartmentRepository.findById(id);
    }
    @GetMapping("/ByLocation")
    public @ResponseBody Iterable<appartment> getApartmentsByLocation(@RequestParam("country") String country,@RequestParam("city")String city
            ,@RequestParam("neighborhood")String neighborhood) throws  JSONException
    {

        String Location=country+"+"+ city +"+"+ neighborhood;
        return appartmentRepository.findBylocationOrderByPriceAllIgnoringCase(Location);
        // return null;

    }
    @GetMapping("/ByLocation/Dates")
    public @ResponseBody Iterable<appartment> getApartmentsByLocationDates(
            @RequestParam("capacity") Integer capacity,
            @RequestParam("startD")String st, @RequestParam("endD")String end,
            @RequestParam("country") String country,@RequestParam("city")String city
            ,@RequestParam("neighborhood")String neighborhood) throws  JSONException
    {

        String Location=country+"+"+ city +"+"+ neighborhood;
        List<appartment> opt=this.appartmentRepository.findByLocationAndCapacityOrderByPriceAllIgnoringCase(Location,capacity);
        Iterator itr = opt.iterator();
        while (itr.hasNext())
        {
            appartment app=(appartment)itr.next();
            if(!app.getDates().contains(st) || !app.getDates().contains(end))
                itr.remove();
        }
        return opt;
        // return null;
    }
    @DeleteMapping("user/appartment")
    public @ResponseBody String DeleteApartment(@RequestParam Integer id) throws JSONException{

        Optional<appartment> temp=appartmentRepository.findById(id);
        if(!temp.isPresent())
            return "ERROR";
        this.appartmentRepository.delete(temp.get());
        return "OK";
    }
    @PostMapping("user/updateAppImage")
    public @ResponseBody String updateAppImage(@RequestParam("imgFile") MultipartFile file,@RequestParam("id")Integer id) throws IOException {
        appartment temp=this.appartmentRepository.findById(id).get();
        System.out.println("fuck me");
        temp.setMain_pic(file.getBytes());
        this.appartmentRepository.save(temp);
        return "OK";
    }
    @PostMapping("user/updateAppDescription")
    public @ResponseBody String updateAppDescription(@RequestBody String jsonStr) throws JSONException {
        JSONObject obj=new JSONObject(jsonStr);
        appartment n=this.appartmentRepository.findById(obj.getInt("id")).get();
        if(n==null)
            return "ERROR";
        else
        {
            n.setDescription(obj.getString("description"));
            this.appartmentRepository.save(n);
            return  "OK";
        }
    } 
}
